name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, order, store, user]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit message
        id: commit_message
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Determine changed directories
        id: changes
        run: |
          git fetch origin main
          git diff --name-only ${{ github.event.before }} origin/main > changed_files.txt
          if grep -qE '^${{ matrix.service }}/' changed_files.txt; then
            echo "Changes detected in ${matrix.service} directory."
            touch ${matrix.service}_changed.txt
          else
            echo "No changes in ${matrix.service} directory."
            echo "No changes" > ${matrix.service}_changed.txt
          fi

      - name: Build and push Docker image for ${{ matrix.service }}
        if: steps.changes.outputs.${{ matrix.service }}_changed != 'No changes' && steps.commit_message.outputs.message contains '[${{ matrix.service }}]'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: 480936841767
        run: |
          cd ${{ matrix.service }}
          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-8)
          make build
          docker tag ${{ matrix.service }}:latest 480936841767.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interface-app:${{ matrix.service }}-${IMAGE_TAG}
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          docker push 480936841767.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/interface-app:${{ matrix.service }}-${IMAGE_TAG}
